export enum Permission {
  // Orders
  ORDERS_VIEW = 'ORDERS_VIEW',
  ORDERS_MANAGE = 'ORDERS_MANAGE',
  
  // Products
  PRODUCTS_VIEW = 'PRODUCTS_VIEW',
  PRODUCTS_MANAGE = 'PRODUCTS_MANAGE',
  
  // Categories
  CATEGORIES_VIEW = 'CATEGORIES_VIEW',
  CATEGORIES_MANAGE = 'CATEGORIES_MANAGE',
  
  // Vouchers
  VOUCHERS_VIEW = 'VOUCHERS_VIEW',
  VOUCHERS_MANAGE = 'VOUCHERS_MANAGE',
  
  // Customers
  CUSTOMERS_VIEW = 'CUSTOMERS_VIEW',
  CUSTOMERS_MANAGE = 'CUSTOMERS_MANAGE',
  
  // Store Settings
  STORE_SETTINGS = 'STORE_SETTINGS',
  
  // Integrations
  INTEGRATIONS_VIEW = 'INTEGRATIONS_VIEW',
  INTEGRATIONS_MANAGE = 'INTEGRATIONS_MANAGE',
  
  // Staff Management
  STAFF_MANAGE = 'STAFF_MANAGE',
}
